# Generated by Django 5.2.1 on 2025-05-25 14:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=200)),
                ('year', models.IntegerField()),
                ('price', models.FloatField()),
                ('cover', models.CharField(max_length=200)),
                ('rating', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('rating', models.IntegerField()),
                ('review', models.CharField(max_length=2000)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bym.album')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bym.user')),
            ],
        ),
    ]
