# Generated by Django 5.2.1 on 2025-05-25 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bym', '0003_alter_album_id_alter_review_id_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='cover',
            field=models.ImageField(upload_to='album_covers'),
        ),
    ]
