# Generated by Django 5.2.1 on 2025-05-25 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bym', '0003_alter_album_id_alter_review_id_alter_user_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='BymUser',
        ),
    ]
