# Generated by Django 5.2.1 on 2025-05-25 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bym', '0004_alter_album_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='rating',
            field=models.FloatField(default=0.0),
        ),
    ]
