# Generated by Django 5.2.1 on 2025-05-25 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bym', '0004_rename_user_bymuser'),
        ('bym', '0005_alter_album_rating'),
    ]

    operations = [
    ]
