# Generated by Django 5.2.1 on 2025-05-25 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bym', '0007_alter_review_user_delete_bymuser'),
        ('bym', '0007_author_alter_album_author'),
    ]

    operations = [
    ]
