# Generated by Django 5.2.1 on 2025-05-25 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bym', '0008_merge_20250525_2033'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='quantity',
            field=models.IntegerField(default=0.0),
        ),
    ]
